### ISSUE TITLE
How to use inline option?

### ISSUE THREAD

**Issue by CristianGOEN** [Sovendus-GmbH/Sovendus-Generic-WebView-App-Integration-Voucher-Network-and-Checkout-Benefits#1]
It says:

```
In case you choose the inline Sovendus banner make sure the

is placed where you want the banner to appear. In case you use the sticky banner, the position of the div doesnt matter.
```

How do you implement this option? 
I want to achieve to get sovendus banner inside a div with custom height and width instead of an iframe, is it possible?

**Comment by sov-brandstaetter** [comment]
Hi @CristianGOEN  
I think Verena already got back to you. This repo is only mobile app integrations. Its similar to the web integration but slightly differnet. This would be the generic docs for web: https://github.com/Sovendus-GmbH/Sovendus-generic-documentation-for-Voucher-Network-and-Checkout-Benefits
The integration is the same for inline and overlay banners, only difference is the configuration for it on our (Sovendus) side.
Best regards
